= Фундаментальная психология №1.
v1.0, 2020-05-09
:example-caption!:
:sectnums:
:sectnumlevels: 2

== Что такое душа?

=== Įvadas - fundamentali psichologija

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=60&end=393" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Tam, kad susidaryti įspūdį apie tai kas yra psichologija ir psichiatrija kaip šiuolaikinė disciplina, šiuolaikinis mokslas, šiuolakinė praktika, šiuolakinė kryptis tapusi tokia populiari, kad beveik kiekvienas dabartinis vakarų civilizacijos žmogus vienaip ar kitaip susidūręs įvairiais savo gyvenimo momentais, bet tam, kad kalbėti apie šiulaiknę psichologiją kaip discipliną, kaip metodą, kaip mokslą, kaip praktiką aišku būtina pažvelgti į tai kas buvo prieš ją.
Todėl, kad šie du terminai kurie sudaro pavadinimą psichologija - psiuche - siela graikiškai ir logos, logija - mokslas, disciplina aišku nusiunčia mus link kažkokių konceptų, kurie turi žymiai senesnę ir žymiai sensnę istoriją, kilmę.
Bet galime pasakyti, kad psichologija tai mokslas apie sielą, taip bent seka iš analizuojant šiuos du terminus.
Bet tame jau randasi principilus triukas, todėl, kad, kada gi atsiranda šis mokslas psichologija?
Griežtai kalbant pats terminas psichologija atsiranda tik 18 amžiuje, o kaip disciplina jis atsiranda 19 amžiuje, net arčiau jo galo, o išpopuliarėja tik 20 amžiuje.
Bet mes žinome, kad būtent šį periodą dabartinis mokslas, dabartinė epistemologija statoma ant visai kitų principų, tai yra naujas laikas 18, 19, 20 ir 21 amžiuose aplamai neigia sielą.
Tai yra psichologija mokslas apie sielą atsiranda būtent tada ir susiformuoja į savarankišką kryptį kada žmogus ne tik pamiršta kas yra siela, bet stato savas teorijas, apie būtį, žmogų, pasaulį, visuomenę išnešdama šią sielą už skliaustų, arba interpretuodama ją kažkokiu neįsivaizduojamu tradicijos atžvilgiu būdu arba aplamai ją neigia.
Psichiatrija tai du terminai psiche - siela ir jatrija - gydymas, tai yra sielos gydymas.
Psichologija tai kas tyrinėja sielą, dar psichologija gali būti konsultacija, o psichiatrija tai kada konsultacijos nepakanka.
Psichologija gali praryti psichiatrijos terminą, jeigu mes suskirstysime psichologiją laipsniais: yra bendra psichologija kuri tiria sielą, yra konsultacinė psichologija, yra griežta taikomoji psichologija klinikinė pagalba.
Tai yra jau pačiame psichologijos pagrinde.
Tai yra psichologija ir psichiatrija apeliuoja į sielą, kurios nėra.
Paradoksas pasirodo pačioje šios disciplinos atsiradimo pradžioje.
Tai ką gi tiria psichologija ir ką išgydo psichiatrija, jei tas kultūrinis ir epistemologinis, mokslinis kontekstas, kuriame ši disciplina vystosi pastatytas ant sielos neigimo.
Kad suprasti šį paradoksą reikia atlikti rimtą ekskursą į tą pasaulį kuris buvo prieš psichologijos atsiradimą, tam kad apibrėžti šios disciplinos geniologiją.

=== Psiche semantika.
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=393&end=586" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Ši lekcija skirta tam kas vadinosi siela iki atsirado psichologijos mokslas.
Tam kad mums tiksliai suprasti psichologijos discipliną būtina parodyti sielos amonimo semantiką šioje disciplinoje ir to apie ką buvo terminas siela iki atsirandant psichologijai ir net giliau savose šaknyse.
Mums reikia suprasti pradinę žodžio psiche reikšmės semantiką tam, kad suprasti su kokiu pradiniu baziniu konceptu psichologija turėjo reikalą, net jei ji suprato po sielą kažką kitą.
Dar daugiau psichologijos mokymas turi prasidėti būtent nuo to.
Būtina sudti šalia psichologijos mokslą ir tai ką vadino siela iki atsiradus šiais disciplinai.
Jei mes šios operacijos neatliksime, jei numosime ranka ir pasakysime - na dabartinė psichologija suprantama savo tyrinėjimo objektą apytiksliai tą patį kaip ir iki mokslo periodo religinėje visuomenėje suprato po sielos pavadinimu, tada mes atliksime didelę klaidą.
Tie kas bando sudaryti įspūdį, kad egzistuoja kažkoks nenutrūkstamas idėjinimas kontinumas tarp sielos kaip ją suprato tradicinė visuomenė iki atsirandant psichologijai, o psichologija tai šiuolaikinis mokslas, kuri atsirado moderno periode ir gan vėlai 18-19 amžiuje, tada mes padarysime kolosalią klaidą.
Tada šią lekciją skirsime tam kuom buvo siela tose visuomenėse, kuriose psichologijos nebuvo ir negalėjo būti, tose visuomenėse kur naujo laiko supratimas apie žmogų, būtį, kosmosą, pasaulį, gamtą, gyvenimą, mirtį, fiziologiją, mentalumą, mąstymą, materialumą visa tai buvo organizuota kitu būdu nei naujais laikais.

=== Aukos dūmai

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=586&end=871" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Sielos sąvoka skirtingose visuomenėse, kultūrose turėjo ir skirtingą pavadinimą tokį kaip lotynų anima, graikišką psiuche arba graikiška pneuma, sanskrito atman, visas šis supratimų kompleksas formavosi aplink kvėpavimo ir pūstelėjimo idėją.
Tai dvi principialios reikšmės, kurios guli sielos supratimo pagrinde.
Anima irgi reiškia kvėpuoti iš čia animal kvėpuojanti būtybė.
Atman irgi reiškia kvėpuoti.
Thiuo graikiškas žodis reiškia kvapo plitimas nuo aukos, tai deginamo ėriuko, jaučio, aukos dūmai arba kvapas kurie kyla kažkur į viršų.
Šis judėjimas, procesas prisodrinto sudegintos aukos aromato.
Graikiškas žodis theo tai ta butybė kuriai skirta šis aromato srautas.


===  Vėjas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=871&end=1275" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
Pagrindinis sielos konceptas tradicinėse visuomenėse(indų europiečių etimologijose) tai: nematomumas, lengvumas, galingumas, judėjimas. Tai yra sielos charakteristikos elementai.
Pas graikus siela buvo simbolizuojama drugeliu. Tai yra drugelis lengvas, tik skirtingai nei siela matomas, bet jis judantis, impulsyvus ir jo lengvi sparnai praktiškai besvoris kūnas nurodo į analogiškas sielos savybes.
Reikia atkreipti dėmesį, kad kuo giliau mes pasineriame į senovę tuo labiau akcentuojamas ne lengvutis kvėpavimas, o pūtimas.
Tai yra pačiame sąvokos pagrinde yra prisodrintas deginamos aukos dūmų kilimas į dangų pas Dievą, kuriam tai ir yra skirta.
Tai yra tema, kuri suvedama į vėjo sąvoką.
Vėjyje mes matome raktą į sielos sąvoką.
Tiksliau pasakius tai vienas iš raktų.
Tai kažkas nematomu, judančio ir labai, labai galingas, todėl, kad vėjas gali sulenkti medį pusiau, stipriai pūsdamas gali sugriauti namą, nunešti jo stogą, vėjyje yra kolosali galia, vėjas neša drėgmę, karštį, marą.
Pučiantys vėjai tarsi formuoja kosimnę tvarką, kurie yra nematomi, bet pasireiškia per savo efektus, pasekmes.
Mes nematome vėjo, bet kas gi sulenkė pusiau medį. Mes negalime pamatyti oro judėjimo, bet kas gi priverčia suktis rudens lapus sūkuriu.
Toji nematoma galia kuri aptinkama pagal savus rezultatus palaipsniui pereina į supratimą apie sielą.
Tai labai svarbu, tai kaip vėjas gali pačiupti kažką sunkaus, juk oras lengvas, o vėjas būdamas oru turi sukebėjimą kažką pačiupti ir nunešti, nuplėšti, pargriauti.
Atrodytų oras nejaučiamas, lenvas, permatomas, bet tuo pačiu, kada oras tampa vėju, jis tampa galia prieš kurią neįmanoma priešintis.
Jis pakelia bangas jūroje ir nuskandinti didžiulį laivą.
Tas nematomas silpnas vėjas tam tikromis aplinkybėmis tampa galinga jėga.
Taip pat ir siela būdama nematoma, lengva, permatoma tam tikromis aplinkybėmis įgyja įspūdingą galią.
Iš čia tas supratimas, kad tas oro lengvumas kuris pavirsta vėju atveda mus link sielos tematikos.
Siela tai kas judina kūną.
Tai labai svarbu, kad siela nematoma, bet aptinkama pagal jos veiklos pasekmes.
Siela ne tai kas juda, bet tai kas judina.
Nematomai judina viską.
Tai ne ritmiškas kvėpavimas, bet sugebėjimas pačiupti ir priversti skristi, bėgti, plaukti, šokinėti, nardyti, pilti aukštyn, blaškytis.
Ta galia valdyti nematomu vėjišku valdymu.
Mes nematome vėjo, bet matome, kaip jis juda: mišku, lauku, per šakas, per žolę.
Lygiai taip pat mes nematome sielos, bet matome, kad ji pačiupo kūną, privertė jį begti, ranką mesti ietį, privertė blizgėti akis, įtempė sunkų lanką, griūti, kristi.
Tai yra vienas iš etimologinių aspektų. Jis taip būdingas ne tik indo europiečiams bet ir kitoms kultūroms.
Toji vėjo, nematomos galios metafora, bet galingos jėgos sąvoka guli sielos suvokime.

===  Siaubas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=1275&end=1544" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++


Antrasis sielos rakursas susijęs su siaubu.
Iš čia anglų kalbos žodis ghost - vaiduoklis.
Tai kas sukelia siaubą ir košmarą, tai kas ateina naktį.
Tai kažkoks atsirandantis iš niekur, bet sukeliantis siaubą ir košmarą pradas.
Tai kažkoks panikos priepolis.
Tai taip pat vėjo gūsis, bet jo blogame pavidale, blogame išmatavime.
Tai susiję su naktimi, su netikėtumu.
Tai yra nematomumas, kuris tampa galingu.
Tai oras, kuris tampa vėju. Kažkas tamsioje naktyje iškrentantis dar tamsesniu.
Tamsi siela užpuolanti žmogų ir pažadina jame siekį bėgti.
Tas tamsus sielos išmatavimas išties gali būti laikomas kaip mūsų pačių susitikimas su sava siela.
Todėl, kad mūsų siela ne pilnai mums priklauso, ji nepriklauso kūnui, o greičiau kūnas priklauso sielai.
Ir staiga atėjusi dvasia paralyžuoja žmogaus dėmesį ir valią, kuris suakmenėja ir yra šios atėjusios iš tamsos nežinomos būtinybės auka, mūsų kūnas yra šios dvasios auka, tai yra mūsų savos sielos.
Mūsų sava siela sukelia kūnui panikišką siaubą.
Jeigu mes susitipatiname su savo kūnu, tai tas kas jį judina - gali būti suvokiama kaip siaubingas viduje mūsų esantis pradas.
Šiuo atveju susitikimas su siela gali būti traumuojanti patirtimi.
Todėl mes neturime būti atsipalaidavę, siela tarsi drugelis, bet ji gali tapti grobuonimi, tai drugelis-šiksnosparnis, drugelis-pelėda, drugelis-erelis.
Tai vėjas karalius, kuris pučiau kiaurai per mus, ima mus įkaitais, kaip naktyje atsiradusi dvasia ima įkaitu tą kam nepasisekė susidurti su ja.
Tai labai svarbus apibrėžimas.



===  Mirtis/protėvis

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=1544&end=2070" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Dar vienas aspektas - mirtis.
Čia mes turime reikalų su žymiai archaiškesniais supratimais einančiais į gilias kultūras, gal net į proto indo europietiškas.
Daugumas ypač archaiškų kultūrų turi omenyje protevio būtį.
Tai yra čia tas kvėpavimas, kuris valdo kaip asmeninis vėjas, uraganas, siaubo šaltinis valdo mūsų kūnu jis įgyja kai kurios figūros geštalto, kuris susijęs su mirusių pasauliu.
Tai yra siela mumyse tai kažkoks mirusių pasaulio elemntas mumyse.
Galima sielą pavadinti protėviu, kažkokiu lavonu, anapusinio pasaulio elementu.
Tai yra siela mumyse yra kažkas nematomo ir susijusi su tuo kada kūnas nustoja egzistavęs.
Kada kūnas nustoja egzistavęs tada siela arba protėvis nesiliauja egzistavęs.
Kitais žodžiais supratimas apie kūną šio protėvio atžvilgiu, čia mes dar nežinome kurioje vietoje patalpinti mūsų asmenybę prie to mes priesime vėliau, bet apie kūną kuris mums duotas, kuris matomas, kuris susijęs su mumis tai viena pusė, bet kada kūnas miršta, yra, pūva ir daugiau negali judėti, kada vidinis vėjas palieka tą kūną iš tiesų kūnas krenta, o kas jame gyveno, vertė kūna judėti palieka jį.
Tai sukuriamas supratimas apie kažkokį laikino ir amžino santykį, laikino ir nekintančio kur pastovi nekintanti dalis vadinama siela.
Tai yra siela yra tai kas pergyvena kūną ateityje, bet tradicinėse visuomenėse iškyrus kai kurios retus atvejus egizsuoja ciklinio laiko idėja, kaip metų, mėnulio, saulės paros ciklas, siela ne tik pergyvena kūną, bet ir yra prieš kūną.
Tai yra siela įeina į kūną, atgaivina, valdo ir išeina iš kūno, o paskui arba vėl ciklas kartojasi, arba randasi kažkur nekūniškoje sferoje.
Bet dažniausiai dauguma senovės religinių mokymų kalba, kad egzistuoja kažkoks pastovus amžinas nemirtingo prado/protėvio grįžimas, kuris įeina į kūdikį, gyvena kartu su juo, veda, gimdo naujus kūdikius, miršta ir grįžta.
Tai yra šiam protėvio judėjime ratu realizuojama vėjo, kvėpavimo amžinybė.
Tai atveda mus prie supratimo apie kažkokią eksperimentinę sielos tradicinėje visuomenėje patirtį.
Dvasia yra tai kas lieka po kūno mirties.
Dvasia yra tai kas ateina į kūną kada kūnas tampa gyvu.
Dvasia tai yra tas miręs daiktas, kuris pagimdo gyvenimą ir tas gyvas daiktas gyvenimo užgesimo metu.
Matome, kad gyvenimas ir mirtis tradicinėje visuomenėje labai sudėtingu būdu persipynę tarp savęs.
Juk kada siela ateina į kūną ji jį atgaivina, o pati atgyja kada kūnas miršta.
Iš čia supratimas apie protėvį, senelį, apie tėvus numirėlius, kurie pastoviai cirkuliuoja kiaurai daugybę kūnų išsaugodamą savo giluminį identitetą.
Salavai čia turi giminės sąvoką. Giminė tai cirkuliuojantis protėvis.
Senelis -> tėvas -> sūnus. Todėl tokie vardai buvo dudami, ivanas - petro sūnus, petras - ivano sūnus. Senelis įeina į anūką.
Labai retai tradicinėse visuomenėse buvo kalbama ivanas ivano sūnus, nes reikia duoti seneliui galimybę įsikūnyti.

=== Persona

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=2070&end=22070" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Persona arba kaukė. Tai irgi gan tradicinis supratimas, nes supratimas apie konkretų žmogų, šį žmogų, individą, apie šią asmenybę nesutapo su mūsų.
Žmogų laikydavo kauke, per kurią gyvena dvasia, o iš ko ta kaukė padaryta į tai buvo žvelgiama kaip į antraeilį dalyką.
Todėl asmenybė tai buvo lainino persikirtimo taškas tarp amžinybės ir laikinumo, tas taškas, kur dvi linijos persikerta ant kryžiaus, o paskui vėl išsiskiria.
Todėl žmoguje principialiai buvo galima buvo pakreipti šį supratimą apie asmenyubę, apie tai kas jis, kas tas konkretus žmogus, buvo galima pakreipti vienu metu į du polius.
Žmogus tai yra tai kas po kauke, tas amžinas, tas protėvis, ta dvasia kuri cirkuliuoja kiaurai materiales kaukes ir lieka nekintama.
Dvasia nepriklauso nuo gyvenimo, o gyvenimas priklauso. Dvasia renkasi gyventi jai ar negyventi, taip pat kaip žmogus renkasi devėti jam rūbą tokį ar kitokį.
Kūnas tai yra opcija.


==== Antras momentas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=2570&end=3050" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++


Mes galime paimti ir nustumti ir pasakyti - ne mes laikome žomgų šitą kūną apdovanotą siela įtvirtiname žemiško gyvenimo rėmuose.
Gime, gyvena ir numirė, vat štai tai yra žmogus.
Tada gaunasi, kad žmogus yra tas apdovanota kūnu siela, t.y. siela plius kūnas.
Tai labai retas tradicinėje visuomenėje būdas, bet kartais pasitaikantis.
Bet štai kas įdomu, jeigu mes susiauriname žmogaus sąvoką tik iki žemiško egzistavimo, tada mums teks padaryti sekantį ėjimą, mums teks žmogaus sielą apdovanoti nepriklausomu nuo žmogaus likimu.
Tai yra atskirai žmogus ir atskirai jo siela, t.y. siela net ne jo, bet askirai siela ir atskirai jos žmogus.
Čia gaunasi, kad žmogus ir siela išsiskiria į du polius.
Jeigu pirmu, sokrato atveju žmogus yra siela, mes susitapatiname su tik su siela, tada buvimas kūne arba nebuvimas mums yra tolygu, tai yra tiesiog pasirinkimo klausimas, kitaip nei kūnas, kuris negali būti arba nebūti, o siela gali ir su kūnu ir be kūno ta siela yra ji gali nuspręsti kaip ji elgsis.
Atitinkamai pažvelgus kitu rakursu iš kitos pusės, jeigu mes pasakysime, kad žmogus tai tas kuris turi sielą ir kūną, tai yra žmogus gyvena laiko atkarpoje, kada yra jo kūnas, tada mums teks padayti labai įdomų ėjimą, mums teks padalinti žmogų ir sielą, tada mes pavadinsime sielą protėviu arba dvasia, kuris mus turi.
Tada mes sakome - žmogus yra kažkoks virš žmogaus esančios dvasios instrumentas arba organas.
Žmogus gyvena ne pats, bet protėvis ant jo jodinėja.
Tai labai būdinga daugeliui tautų, apie tai koks yra žmogus.
Jei mes susiauriname žmogų iki jo žemiško egzistavimo, tada mes priversti suteikti jo sielai neprikausomą, suverenaus prado statusą, kuris skiriasi nuo to žmogaus, kuris yra tarsi jo ponas, viršininkas.
Tada siela tampa dvasia arba Dievu arba protėviu, kai kuriose visuomenėse tai vadinama vienodai, tada siela pavirsta į tokią gan fundamentalią instanciją, kuios nepaliečia gyvenimas ir net pats žmogus, jeigu mes sakome kad gimstame ir gyvename iki mirties - tai yra žmogus, o siela po mirties nėra žmogus, tada tokiu atveju atsiranda figūra, kuri principialai iš abiejų pusių, iki gimimo ir po gimimo tarsi apibrėžia žmogų, tai vadinasi prortėvis, dvasia arba Dievas, kuris imeta žmogų į gyvenimą, o po to užbaigia, nes jis atšoko savo šokį.
Jei mes sakome, kad žmogus yra tas kuri gyvena kūne, tada jo siela tampa kažkuom savarankišku, autonominiu nuo jo bet be šios sielos žmogus praktiškai pats yra niekas, todėl, kad būtenti ši siela, šis ponas, šis raitelis ant individualaus arklio jis ir varo mažylį tam, kad jis augtų, priverčia jį medžioti, vaikšioti į darbą, turėti šeimą, gimdyti naujus padarus, o paskui jį užmuša.
Atmanas yra brachmanas, ar tik ne apie tai kalba induistinė formulė. 
Mūsų vidinė dalis(Atmanas arba aš) yra aukščiausias Dieviškasis pradas(Brachmanas).
Taip gimsta Brachmanas iš Atmanas, jei mes Atnanas suteikiame Brachmanui vis didesnę ir didesnę reikšme, rezultate jis susilies su Absoliučia Dievybe.

==== Trečias kelias

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=3050&end3320" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Galim dar eiti trečiu keliu.
Galim nustumti tą balansą žemiau link kūno.
Tai labai retas atvejas tradicinėje visuomėnėje.
Galima pasakyti, kad žmogus tai kūnas.
Bet jei mes sakome, kad žmogus tai kūnas, reiškia, kad mes atlikome antrą transcendavimo akciją žemyn.
Jei žmogus kūnas tada iš ties gyvas kūnas yra kažkokia dvasia.
Jei žmogus kūnas tai tas kas gyvena, veikia ir verčia mus judėti tai transcendentinis mūsų pačių atžvilgiu pradas.
Žmogus sutapatina save su instrumentu.
Žmogus sako, aš esu savo paties plaktukas.
Toks supratimas yra labai ekstravagantiškas.
Jeigu žmogus yra kūnas, tada kas tą kūną padaro gyvu, reiškia, kad ne žmogus.
Čia supratimas apie sielą ir Dieva žymiai labiau imantenizuotas, dar labiau susiaurintas ir jei pirmu atveju supratimas apie sielą sutapdavo su mūsų aš, antru atveju siela tapdavo absoliučiu ponu tam žmogui gyvenančiam to pono skirtoje laiko teritorijoje, bet jei mes pasakysime, kad mes kūnas, kad žmogus yra kūnas, nustumsime kaukę žemyn, tada mes esame priversti pripažiniti tą individualų pradą, kuris suteikią mūsų kūnui kažkokias orientacijas statusą apie trancendentinį supratimą apie kažką kitą.
Supratimas apie žmogų kaip apie kūną yra labai ekstravagantiškas ir daro jo individualų egzistavimą jo ponu, čia vyksta sudvejinimas kita  linija.
Jei mes manome, kad žmogus yra tik kūnas, tada iš tiesų žmogus yra kažkokios individualio esybės instrumentas, vergas, auka kuri irgi gyvena tik nuo gyvenimo pradžios iki galo.
Tada nemirtinga siela tamp tokia tolima, tokia principialiai nepasiekiamas pradas, kad apie jį sunku kalbėti.
Aišku tai ekscesas, su tokiu supratimu mes nesusiduriame, bet daleisti visas tris žmogaus išsidėstimo pozicijas mes galime.
Kiekvienoje tradicinėje visuomėje supratimas apie žmogų varijuojasi ant šios skalės.
Mes suradome tris vietas žmogui: Sokrato žmogus tai siela, žmogus tai kūnas ir siela ir žmogus tik kūnas, bet tarp šių trijų principialių pozicijų randasi daugybė niuansų, toje pačioje ašyje, bet kitose proporcijose.

==== Pirmasis būdas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=3320&end3738" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Dabar galima, patogumo dėlei paimti klasikinę graikų filosofija ir dalinai ikisokratikus tam, kad mes turėtume šims trims supratimams orientyrus ir apžvelgti juos trijuose skirtingose kultūrose.
Aš nenoriu pasakyti, kad jie identiški kitiems supratimams apie sielą, bet jie gali būti gan naudingi tipologizuojant.
Taigi dar kartą grįžkime prie supratimo, kad žmogus tai siela.
Neatsitiktinai mes susiduriame su tuo pas Platoną Alkiviado dialoge, kur šią idėją išsako Sokratas.
Tai kažkoks galime pasakyti antropologinis maksimalizmas, kuris sako, kad dvasia yra protėvis, kad siela yra dvasia, dvasia yra Dieviškasis išmatavimas esantis mumyse.
Ir, kad tik tai yra žmogus ir atitinkamai žmogus yra kažkoks apvalkalas, o ne jis pats o kūnui nesuteikiama jokios reikšmės.
Ant to pastatytas supratimas apie sielą pas Platoną ir pas jo pasekėjus ir viskas kas vienaip ar kitaip pažymėta platonizmu, o tai labai didelis filosofijos spektras ir krikščionybėje tai labai fundamentlu, ir kitose savarankiškose tradicijose, pavyzdžiui induizme arba zaostrizme mes matome labai panašų supratimą.
Platonas sako, kad sieloje randasi trys lygmenys: protingas pradas sutapatinamas su vežėju, kuris vairuoja vežimą, paskui aistros pradas, kas yra norai, troškimai ir kūniškas pradas, kuris traukiasi link kūniškumo.
Tokia trejopa siela kur dominuoja vežėjas, kuris ir yra tos sielos prasmė, tai kažkoks intelektualus pradas, beveik Diviškas pradas, todėl, kad Fedre Platonas sako apie tai, kad žmoguas siela, tas vežėjas dalyvauja dieviškosiose jojimo varžybose ir tada kada padaro klaidą, tada krenta į kūną ir per meilę išminčiai, tiesai grįžta į savo kelią.
Neoplatonikai detaliai išvysto, Plotinas sako, kad siela niekaip amžinai nepaveikiama žmogaus egzistavimu kūne, todėl siela šalta, beveik Dieviška.
Yra žmogus kūne, nera, sielos tai nejaudina ji stebi aukščiausią protą, tai yra jos pagrindinė būsea.
Siela proto atvžilgiu yra kiek nustumta, todėl siela turi kuom užsiimti, ji stebi didį, amžina protą.

==== Antrasis būdas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=3738&end4140" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Antrasis būdas, tai kur siela ir kūnas persikerčia žymiai apčiuopiamiau, ten kur žmogus yra ta intersekcija, tarp sielos ir žmogaus, ten kur kūnas igyja materialumą, mes turime Aristotelio supratimą.
Aristotelio požiūriu, kuris fundamentaliai revizavo savo mokytojo Platono filosifiją siela kažkiek pakeičia savo reikšmę.
Tai yra įsivaizduoti sielą be kūno Aristotelis negali, bet vis vien jis sako, kad yra tokia viena siela be kūno, tai yra Dievas.
Ji randasi centre, o visos kitos butybės turi ir sielą ir kūną, o jų siela tai judėjimas link Dievo, link to kas yra gryna siela, tik dievas yra gryna siela, o visa kita yra sielos ir kūno derinys.
Tai yra žymiai proporcionalesnis sielos vaizdas, o žmogus tai ne pati Dievybė, bet kelias link tos Dievybės.
Žmogus kūniškas, žmogų turi siela, sielai paklusnus kūnas, siela judina kūną, bet kaip ji judina tą kūną?
Aristotelio požiūriu viskas suvedama link mokymo apie judėjimą.
Siela kaip entilechija judina kūną link savęs pačios.
Siela tai judėjimas link tikslo.
Tai tikslas ir judėjimas link jos.
Bet tikslas ji yra žmogui kaip jis yra, todėl tas tikslas yra biški nepasiekiamas, o judėjimas žmogaus tapimui.
Čia tapimas įgyja ne tiesiog gimimo ir mirties bruožą, kaip pas Platonikus, o tapimas įgyja kažkokį žmogaus procesą, judėjimą link savos sielos.
Kuri ir yra vienu metu ir yra duota jam ne iki galo.
Švariame pavidale siela tai Dievo siela, o žmogus yra judėjimas link šios sielos.
Čia mes matome tai apie ką mes kalbėjome kada apibūdinome žmogų kaip kažką tarpiško, kaip žmogų glaudžiai susijusį su kūnu.
Tai labai Aristoteliška, siela turi autonomiją, viršiškumą, turinį, Dieviškumą.
Žmogus turi žmogaus sielą, gyvūnai gyvūnišką, augalai augališką, bet žmogaus siela yra arčiau tikslo.
Visos šios sielos turi Dievišką sielą kaip tikslą.
Tai skirtingi Dieviškosios sielos gyvenimo intencyvumo laipsniai.
Čia siela yra ir siela kažkokia prasme nepriklausoma, nuo kūno ir žmogaus, bet čia nėra žmogaus kuris galėtų būti pavaizduotas kaip egzistuojantis be sielos ir be kūno.
Žmogaus kūniškumas įgyja jos imamentinio konkretumo ypatingą bruožą.
Tas imanentinis žmogaus konkretiškumas organizuotas ne linijoje nuo gimimo link mirties, ne horizontaliai laike, bet vertikaliai jo laiko atžvilgiu.
Pas Aristotelį atsiranda naujas papildomas laikas, be horizantalaus gyvenimo laiko, turi vertikalų horizontą, kuris perkerta laiko horizontalę, tai yra sielos laikas - etilechija.
Aristotelis sako, kad siela apčiuopia tą vertikalią orientaciją, tą kelią kuriuo ji turi eiti tai yra sofijos momentas.
Gyvenimo eigoje žmogus sukaupia kažkokį bagažą, tai vadinama fronesis, bet tai ne tas žinojimas.
Teisingas žinojimas tai judėjimas vertikaliai link savos Dieviškosios esmės.
Tokiu būdu Aristotelio mokymas apie sielą yra antroji versiją apie sielą ir aišku daugumoje tradicijų ir tolimų nuo graikiškos mes galima pamatyti tokį supratimą.


==== Trečias būdas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=4140&end41400" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Demokritas, Epikūras ir kiti graikų materialistai kalba, kad viskas kas yra materialu, sudaryta iš atomų.
Demokritas kalba, kad siela taip pat sudaryta iš atomų.
Žmonių sielos atomai silpniau susikabinę nei Dievų todėl ji subyra.
Jie sako, kad siela yra ji yra žymiai aukščiau nei kūnas, jei kūno atomai silpnai laikosi pagal Demokiritą ir sura po mirties, sielos atomai tvirtesni, todėl suyra vėliau, todėl su mirusiais galima bendrauti ir pats Demokritas laiką leisdavo kapinėse bandydamas iškviesti tas dar nesuirusias sielas.
Demokrito estafetę perima Epikūras ir sako, kad žmogus pilnai materialus, kol gyvna tol gyvena, o kada miršta nieko iš jo nelieka.
Jis sako, kad yra absoliutus materialus, kurio išorėje nėra nieko, tada jeigu nieko daugiau nėra todėl viskas materialu.

Tradicinėje visuomenėje totaliai dominuoje pirmi du sielos modeliai, t.y, kad siela yra kažkas visai dieviško pilnai nepriklausoma nuo kūno, antras modelis tai siela sukryžminta su kūnu.
Platonizmas ir Aristotelizmas yra populiariausio sielos interpretacijos modeliai, kaip klasikinėse religinėse filosifijose ir mistiniuose mokymuose, taip ir pačiuose archaiškiausiuose kultuose.

Tai gali būti mus vedantis kelias, kad suprasti sielos koncepto semantiką tradicinėje visuomenėje.
