= Фундаментальная психология №1.
v1.0, 2020-05-09
:example-caption!:
:sectnums:
:sectnumlevels: 2

== Что такое душа?

=== Įvadas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=60&end=80" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

=== todo
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=286&end=394" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

===  todo

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=585&end=871" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

===  Vėjas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=871&end=1275" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
Pagrindinis sielos konceptas tradicinėse visuomenėse(indų europiečių etimologijose) tai: nematomumas, lengvumas, galingumas, judėjimas. Tai yra sielos charakteristikos elementai.
Pas graikus siela buvo simbolizuojama drugeliu. Tai yra drugelis lengvas, tik skirtingai nei siela matomas, bet jis judantis, impulsyvus ir jo lengvi sparnai praktiškai besvoris kūnas nurodo į analogiškas sielos savybes.
Reikia atkreipti dėmesį, kad kuo giliau mes pasineriame į senovę tuo labiau akcentuojamas ne lengvutis kvėpavimas, o pūtimas.
Tai yra pačiame sąvokos pagrinde yra prisodrintas deginamos aukos dūmų kilimas į dangų pas Dievą, kuriam tai ir yra skirta.
Tai yra tema, kuri suvedama į vėjo sąvoką.
Vėjyje mes matome raktą į sielos sąvoką.
Tiksliau pasakius tai vienas iš raktų.
Tai kažkas nematomu, judančio ir labai, labai galingas, todėl, kad vėjas gali sulenkti medį pusiau, stipriai pūsdamas gali sugriauti namą, nunešti jo stogą, vėjyje yra kolosali galia, vėjas neša drėgmę, karštį, marą.
Pučiantys vėjai tarsi formuoja kosimnę tvarką, kurie yra nematomi, bet pasireiškia per savo efektus, pasekmes.
Mes nematome vėjo, bet kas gi sulenkė pusiau medį. Mes negalime pamatyti oro judėjimo, bet kas gi priverčia suktis rudens lapus sūkuriu.
Toji nematoma galia kuri aptinkama pagal savus rezultatus palaipsniui pereina į supratimą apie sielą.
Tai labai svarbu, tai kaip vėjas gali pačiupti kažką sunkaus, juk oras lengvas, o vėjas būdamas oru turi sukebėjimą kažką pačiupti ir nunešti, nuplėšti, pargriauti.
Atrodytų oras nejaučiamas, lenvas, permatomas, bet tuo pačiu, kada oras tampa vėju, jis tampa galia prieš kurią neįmanoma priešintis.
Jis pakelia bangas jūroje ir nuskandinti didžiulį laivą.
Tas nematomas silpnas vėjas tam tikromis aplinkybėmis tampa galinga jėga.
Taip pat ir siela būdama nematoma, lengva, permatoma tam tikromis aplinkybėmis įgyja įspūdingą galią.
Iš čia tas supratimas, kad tas oro lengvumas kuris pavirsta vėju atveda mus link sielos tematikos.
Siela tai kas judina kūną.
Tai labai svarbu, kad siela nematoma, bet aptinkama pagal jos veiklos pasekmes.
Siela ne tai kas juda, bet tai kas judina.
Nematomai judina viską.
Tai ne ritmiškas kvėpavimas, bet sugebėjimas pačiupti ir priversti skristi, bėgti, plaukti, šokinėti, nardyti, pilti aukštyn, blaškytis.
Ta galia valdyti nematomu vėjišku valdymu.
Mes nematome vėjo, bet matome, kaip jis juda: mišku, lauku, per šakas, per žolę.
Lygiai taip pat mes nematome sielos, bet matome, kad ji pačiupo kūną, privertė jį begti, ranką mesti ietį, privertė blizgėti akis, įtempė sunkų lanką, griūti, kristi.
Tai yra vienas iš etimologinių aspektų. Jis taip būdingas ne tik indo europiečiams bet ir kitoms kultūroms.
Toji vėjo, nematomos galios metafora, bet galingos jėgos sąvoka guli sielos suvokime.

===  Siaubas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=1275&end=1544" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++


Antrasis sielos rakursas susijęs su siaubu.
Iš čia anglų kalbos žodis ghost - vaiduoklis.
Tai kas sukelia siaubą ir košmarą, tai kas ateina naktį.
Tai kažkoks atsirandantis iš niekur, bet sukeliantis siaubą ir košmarą pradas.
Tai kažkoks panikos priepolis.
Tai taip pat vėjo gūsis, bet jo blogame pavidale, blogame išmatavime.
Tai susiję su naktimi, su netikėtumu.
Tai yra nematomumas, kuris tampa galingu.
Tai oras, kuris tampa vėju. Kažkas tamsioje naktyje iškrentantis dar tamsesniu.
Tamsi siela užpuolanti žmogų ir pažadina jame siekį bėgti.
Tas tamsus sielos išmatavimas išties gali būti laikomas kaip mūsų pačių susitikimas su sava siela.
Todėl, kad mūsų siela ne pilnai mums priklauso, ji nepriklauso kūnui, o greičiau kūnas priklauso sielai.
Ir staiga atėjusi dvasia paralyžuoja žmogaus dėmesį ir valią, kuris suakmenėja ir yra šios atėjusios iš tamsos nežinomos būtinybės auka, mūsų kūnas yra šios dvasios auka, tai yra mūsų savos sielos.
Mūsų sava siela sukelia kūnui panikišką siaubą.
Jeigu mes susitipatiname su savo kūnu, tai tas kas jį judina - gali būti suvokiama kaip siaubingas viduje mūsų esantis pradas.
Šiuo atveju susitikimas su siela gali būti traumuojanti patirtimi.
Todėl mes neturime būti atsipalaidavę, siela tarsi drugelis, bet ji gali tapti grobuonimi, tai drugelis-šiksnosparnis, drugelis-pelėda, drugelis-erelis.
Tai vėjas karalius, kuris pučiau kiaurai per mus, ima mus įkaitais, kaip naktyje atsiradusi dvasia ima įkaitu tą kam nepasisekė susidurti su ja.
Tai labai svarbus apibrėžimas.



===  Mirtis/protėvis

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=1544&end=2070" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Dar vienas aspektas - mirtis.
Čia mes turime reikalų su žymiai archaiškesniais supratimais einančiais į gilias kultūras, gal net į proto indo europietiškas.
Daugumas ypač archaiškų kultūrų turi omenyje protevio būtį.
Tai yra čia tas kvėpavimas, kuris valdo kaip asmeninis vėjas, uraganas, siaubo šaltinis valdo mūsų kūnu jis įgyja kai kurios figūros geštalto, kuris susijęs su mirusių pasauliu.
Tai yra siela mumyse tai kažkoks mirusių pasaulio elemntas mumyse.
Galima sielą pavadinti protėviu, kažkokiu lavonu, anapusinio pasaulio elementu.
Tai yra siela mumyse yra kažkas nematomo ir susijusi su tuo kada kūnas nustoja egzistavęs.
Kada kūnas nustoja egzistavęs tada siela arba protėvis nesiliauja egzistavęs.
Kitais žodžiais supratimas apie kūną šio protėvio atžvilgiu, čia mes dar nežinome kurioje vietoje patalpinti mūsų asmenybę prie to mes priesime vėliau, bet apie kūną kuris mums duotas, kuris matomas, kuris susijęs su mumis tai viena pusė, bet kada kūnas miršta, yra, pūva ir daugiau negali judėti, kada vidinis vėjas palieka tą kūną iš tiesų kūnas krenta, o kas jame gyveno, vertė kūna judėti palieka jį.
Tai sukuriamas supratimas apie kažkokį laikino ir amžino santykį, laikino ir nekintančio kur pastovi nekintanti dalis vadinama siela.
Tai yra siela yra tai kas pergyvena kūną ateityje, bet tradicinėse visuomenėse iškyrus kai kurios retus atvejus egizsuoja ciklinio laiko idėja, kaip metų, mėnulio, saulės paros ciklas, siela ne tik pergyvena kūną, bet ir yra prieš kūną.
Tai yra siela įeina į kūną, atgaivina, valdo ir išeina iš kūno, o paskui arba vėl ciklas kartojasi, arba randasi kažkur nekūniškoje sferoje.
Bet dažniausiai dauguma senovės religinių mokymų kalba, kad egzistuoja kažkoks pastovus amžinas nemirtingo prado/protėvio grįžimas, kuris įeina į kūdikį, gyvena kartu su juo, veda, gimdo naujus kūdikius, miršta ir grįžta.
Tai yra šiam protėvio judėjime ratu realizuojama vėjo, kvėpavimo amžinybė.
Tai atveda mus prie supratimo apie kažkokią eksperimentinę sielos tradicinėje visuomenėje patirtį.
Dvasia yra tai kas lieka po kūno mirties.
Dvasia yra tai kas ateina į kūną kada kūnas tampa gyvu.
Dvasia tai yra tas miręs daiktas, kuris pagimdo gyvenimą ir tas gyvas daiktas gyvenimo užgesimo metu.
Matome, kad gyvenimas ir mirtis tradicinėje visuomenėje labai sudėtingu būdu persipynę tarp savęs.
Juk kada siela ateina į kūną ji jį atgaivina, o pati atgyja kada kūnas miršta.
Iš čia supratimas apie protėvį, senelį, apie tėvus numirėlius, kurie pastoviai cirkuliuoja kiaurai daugybę kūnų išsaugodamą savo giluminį identitetą.
Salavai čia turi giminės sąvoką. Giminė tai cirkuliuojantis protėvis.
Senelis -> tėvas -> sūnus. Todėl tokie vardai buvo dudami, ivanas - petro sūnus, petras - ivano sūnus. Senelis įeina į anūką.
Labai retai tradicinėse visuomenėse buvo kalbama ivanas ivano sūnus, nes reikia duoti seneliui galimybę įsikūnyti.

=== Persona

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=2070&end=22070" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Persona arba kaukė. Tai irgi gan tradicinis supratimas, nes supratimas apie konkretų žmogų, šį žmogų, individą, apie šią asmenybę nesutapo su mūsų.
Žmogų laikydavo kauke, per kurią gyvena dvasia, o iš ko ta kaukė padaryta į tai buvo žvelgiama kaip į antraeilį dalyką.
Todėl asmenybė tai buvo lainino persikirtimo taškas tarp amžinybės ir laikinumo, tas taškas, kur dvi linijos persikerta ant kryžiaus, o paskui vėl išsiskiria.
Todėl žmoguje principialiai buvo galima buvo pakreipti šį supratimą apie asmenyubę, apie tai kas jis, kas tas konkretus žmogus, buvo galima pakreipti vienu metu į du polius.
Žmogus tai yra tai kas po kauke, tas amžinas, tas protėvis, ta dvasia kuri cirkuliuoja kiaurai materiales kaukes ir lieka nekintama.
Dvasia nepriklauso nuo gyvenimo, o gyvenimas priklauso. Dvasia renkasi gyventi jai ar negyventi, taip pat kaip žmogus renkasi devėti jam rūbą tokį ar kitokį.
Kūnas tai yra opcija.


==== Antras momentas

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/QSaSrhg-Hes?start=2570&end=22070" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++


Mes galime paimti ir nustumti ir pasakyti - ne mes laikome žomgų šitą kūną apdovanotą siela įtvirtiname žemiško gyvenimo rėmuose.
Gime, gyvena ir numirė, vat štai tai yra žmogus.
Tada gaunasi, kad žmogus yra tas apdovanota kūnu siela, t.y. siela plius kūnas.
Tai labai retas tradicinėje visuomenėje būdas, bet kartais pasitaikantis.
Bet štai kas įdomu, jeigu mes susiauriname žmogaus sąvoką tik iki žemiško egzistavimo, tada mums teks padaryti sekantį ėjimą, mums teks žmogaus sielą apdovanoti nepriklausomu nuo žmogaus likimu.
Tai yra atskirai žmogus ir atskirai jo siela, t.y. siela net ne jo, bet askirai siela ir atskirai jos žmogus.
Čia gaunasi, kad žmogus ir siela išsiskiria į du polius.
Jeigu pirmu, sokrato atveju žmogus yra siela, mes susitapatiname su tik su siela, tada buvimas kūne arba nebuvimas mums yra tolygu, tai yra tiesiog pasirinkimo klausimas, kitaip nei kūnas, kuris negali būti arba nebūti, o siela gali ir su kūnu ir be kūno ta siela yra ji gali nuspręsti kaip ji elgsis.
Atitinkamai pažvelgus kitu rakursu iš kitos pusės, jeigu mes pasakysime, kad žmogus tai tas kuris turi sielą ir kūną, tai yra žmogus gyvena laiko atkarpoje, kada yra jo kūnas, tada mums teks padayti labai įdomų ėjimą, mums teks padalinti žmogų ir sielą, tada mes pavadinsime sielą protėviu arba dvasia, kuris mus turi.
Tada mes sakome - žmogus yra kažkoks virš žmogaus esančios dvasios instrumentas arba organas.
Žmogus gyvena ne pats, bet protėvis ant jo jodinėja.
Tai labai būdinga daugeliui tautų, apie tai koks yra žmogus.
Jei mes susiauriname žmogų iki jo žemiško egzistavimo, tada mes priversti suteikti jo sielai neprikausomą, suverenaus prado statusą, kuris skiriasi nuo to žmogaus, kuris yra tarsi jo ponas, viršininkas.
Tada siela tampa dvasia arba Dievu arba protėviu, kai kuriose visuomenėse tai vadinama vienodai, tada siela pavirsta į tokią gan fundamentalią instanciją, kuios nepaliečia gyvenimas ir net pats žmogus, jeigu mes sakome kad gimstame ir gyvename iki mirties - tai yra žmogus, o siela po mirties nėra žmogus, tada tokiu atveju atsiranda figūra, kuri principialai iš abiejų pusių, iki gimimo ir po gimimo tarsi apibrėžia žmogų, tai vadinasi prortėvis, dvasia arba Dievas, kuris imeta žmogų į gyvenimą, o po to užbaigia, nes jis atšoko savo šokį.
Jei mes sakome, kad žmogus yra tas kuri gyvena kūne, tada jo siela tampa kažkuom savarankišku, autonominiu nuo jo bet be šios sielos žmogus praktiškai pats yra niekas, todėl, kad būtenti ši siela, šis ponas, šis raitelis ant individualaus arklio jis ir varo mažylį tam, kad jis augtų, priverčia jį medžioti, vaikšioti į darbą, turėti šeimą, gimdyti naujus padarus, o paskui jį užmuša.
Atmanas yra brachmanas, ar tik ne apie tai kalba induistinė formulė. 
Mūsų vidinė dalis(Atmanas arba aš) yra aukščiausias Dieviškasis pradas(Brachmanas).
Taip gimsta Brachmanas iš Atmanas, jei mes Atnanas suteikiame Brachmanui vis didesnę ir didesnę reikšme, rezultate jis susilies su Absoliučia Dievybe.


