= Aktyvi sąmonė.
v1.0, 2020-06-07
:example-caption!:
:sectnums:
:sectnumlevels: 3

= 1. Skirsnis. Psichonetinės technikos

== Skyrius. Valios psichotechnikos bendrame psichotechnikų kontekste

=== 5.1. Техники формирования визуальной плоскостной деконцентрации внимания

Изучение техник деконцентрации внимания удобнее начинать с визуальной деконцентрации внимания. В современных обществах культура перцептивной работы с пространством несравнимо рафинированнее работы со временем, а именно визуальный канал восприятия и визуальные представления и составляют основу работы с пространством. Основные категории восприятия — фигура, фон, не-восприятие и абстрактные модальные зоны сознания — представлены здесь достаточно наглядно.

Есть множество путей изучения деконцентрации внимания. Один из них подробно описан в моей работе «Деконцентрация». Здесь мы рассмотрим нескольку иную траекторию деконцентративных практик, поскольку рассуждение ведется в контексте задачи формирования активного сознания.

Прежде, чем переходить к практике деконцентрации внимания, следует добиться независи мости перемещения локуса внимания от перемещения взгляда. Это можно сделать, «привязав» неподвижный взгляд к какой-либо точке перед собой и перемещая при этом «пятно» (локус) внимания по визуальной «картинке», сформировавшейся в поле зрения. Для усиления эффекта можно сместить взгляд в левый угол поля зрения, а внимание — в противоположный, а затем начать медленно перемещать взгляд в правый угол, а внимание в левый. При этом следует отметить момент, когда «пятно» внимания и фокус взгляда встречаются, а потом расходятся. Часто такая встреча оборачивается дезорганизацией внимания, что открывает в дальнейшем дорогу для углубленной рефлексивной работы. Модификацией этого упражнения является вращение «пятна» внимания по краям поля зрения в одном направлении (например, по часовой стрелке), а фокуса взгляда — в противоположную. Задача, на первых порах, достаточно сложная, сопровождающаяся, как правило, состоянием некоей «странности».

Эту задачу можно усложнить, окончательно разрывая связь перемещения внимания с движениями глаз. Для этого вводится вертикальное перемещение внимания при горизонтальном перемещении глаз и наоборот. Можно ввести еще более сильные задания — перемещение взгляда плюс не одно, а два «пятна» внимания, движущиеся в противоположных направлениях.

Разнесение локуса внимания и фокуса взгляда — первый шаг на пути реорганизации отношений «Я» и внимания. Внимание обычно управляется взглядом, фокус взгляда привязывает к себе внимание, делает его зависимым от одного из многих действий, совершаемых организмом. Внимание, независимое от перемещения взгляда, начинает напрямую управляться волевым усилием и это открывает дорогу к превращению внимания в пластичный инструмент воли.

Теперь остается разорвать еще две связи внимания — связь с фигурой и связь с объектом внимания.

Внимание — психическая функция, и ее назначение состоит в выделении целостных фигур из общего зрительного строя. Это достаточно автоматизированная функция, и придать ей еще большую произвольность после освобождения от связанности с движением глаз можно, заставив выполнять несвойственную ей работу: превращать поле восприятия не в набор меняющихся фигур, а в фон.

Фон — это то, что находится между фигурами. Опыта осознанного восприятия фона нет. Перемещение внимания в фон, как правило, заканчивается выделением из фона новых фигур, тем самым фигурное структурирование перцептивного поля восстанавливается. Деконцентрация внимания решает проблему выделения фона как отдельной единицы поля восприятия и его осознания, задавая аппарату восприятия неразрешимую задачу — одновременное удержание внимания на десятках и сотнях элементах поля восприятия.

Обычная процедура инициации деконцентрации внимания — распространение внимания от периферии поля зрения к центру. Это принципиальный момент в деконцентрации внимания — закономерности восприятия на периферии поля зрения, значительно менее дифференцированной, чем центральное поле, распространяются на все поле зрения, уравнивая тем самым и периферию, и центр по степени дифференцированности. Внимание охватывает все поле зрения, не выделяя отдельные его элементы в качестве преимущественных. Подчеркнем(и это важно для дальнейшего): деконцентративное внимание охватывает
все поле восприятия, оно не покидает визуальную картинку, а обеспечивает ее восприятие целиком и полностью, превращая ее в единое целое и, таким образом, разрушая ее внутреннюю фигуративную структуру.

Первоначальная неустойчивость деконцентрации внимания, замедляющая изучение техники, должна быть использована во благо всей психонетической практики. Это соответствует общей психонетической логике: любой феномен психической жизни может стать звеном целенаправленной психотехнической разработки. Колебания между обычным вниманием и деконцентра-
тивным становятся начальным феноменом, от которого выстраивается линия рефлексивных психотехник. В самом деле, наблюдение за колебаниями внимания, разрушением и восстановлением деконцентрации внимания, не является процессом внимания, поскольку объектом внимания могут быть лишь восприятия и другие содержания сознания, которые превращаются вниманием в целостные предметы. Наблюдение, которое оставляет внимание как наиболее абстрактную психическую функцию в неприкосновенности, отражает уже не функциональные зоны сознания, а один из трех аспектов чистого «Я». Так закладываются основы будущего построения новой структуры взаимоотношений «Я» и организма сознания.

Когда практикующему кажется, что деконцентрации внимания становится стабильной, вводятся три критерия ее устойчивости и глубины, отражающих три стадии погружения в деконцентрации внимания-состояние.

Первый критерий: деконцентрации внимания не разрушается при появлении в поле зрения движущихся предметов. Так это или нет — легко увидеть со стороны: если внимание выделяет движущийся предмет (т.е., деконцентрации внимания разрушается), то глаза какое-то мгновение сопровождают его, и эти подергивания глазных яблок хорошо заметны.

Более сильный критерий, характеризующий глубину деконцентрации внимания (2-я стадия), — отсутствие движения глаз по отношению к лицу при перемещениях практикующего. Самый простой пример — медленные повороты головы. Если деконцентрации внимания не разрушается и предметы не выделяются из общего фона, то глаза не «цепляются» за предметы и скачкообразных движений
глаз не наблюдаются. Глаза как бы «врастают» в голову. Это характеристика очень глубокого деконцентрации внимания-погружения, когда перцептивные стимулы перестают управлять вниманием и теряют свой принуждающий характер. По отношению к этому критерию возможна специальная тренировка, ускоряющая прогресс в практике.

Первый прием: внимание концентрируется одновременно на крайних точках в правом и левом углах поля зрения. Задача: следить за изменениями в крайних точках при поворотах головы без переноса внимания с одной точки на другую. Потом внимание постепенно распространяется на все поле зрения, фиксируя все изменения, происходящие в каждой точке поля зрения.

Второй прием: соединить указательные и большие пальцы рук так, как это указано на рис. 3. Взгляд «привязывается» к соединению указательных пальцев, а внимание — к треугольнику, образованному большими и указательными пальцами. Перемещая руки одновременно с поворотом головы, можно «увидеть», как выглядит динамичный фон. Постепенно раздвигая руки и фиксируя взгляд между указательными пальцами (рис. 4), можно добиться нужного эффекта.

Третий критерий может показаться достаточно причудливым, но он отражает еще большую устойчивость по отношению к значимым стимулам: сохранение деконцентрации внимания при прямом взгляде в глаза практикующему. Такой визуальный контакт вызывает сильную неконтролируемую реакцию, отражающую систему эмоциональных и социально-статусных взаимоотношений людей. Скачкообразные или плавные движения глаз практикующего при использовании этого приема свидетельствуют о разрушении деконцентрации внимания, отсутствие же реакции на прямой взгляд говорит о степени деконцентрации внимания, достаточной для перехода к следующим техникам, ориентированным на непосредственную работу со смысловыми зонами сознания (3-я стадия).

Иногда уже на ранней стадии изучения деконцентрации внимания (и достаточно часто на 2-й и 3-й стадии) поле зрения практикующего затягивается молочно-белой или молочно-серой пеленой. Это объясняется прекращением саккадических движений глаз и стабилизацией изображения на сетчатке. Пелена может служить критерием ментальной тишины, «внутреннего безмолвия»: любая мысль или возникший в сознании образ, отвлекающие внимание и, следовательно, разрушающие деконцентрации внимания, отражаются в микродвижениях глаз, восстанавливающих визуальное восприятие.

=== деконцентрации внимания по полю зрения при закрытых глазах

Это особый вид деконцентрации внимания, отличающийся от визуальной деконцентрации внимания с открытыми глазами. Поле зрения при закрытых глазах — граница между внутренним и внешним мирами. Представитель внешнего мира — неопределенные
пятна, проплывающие в поле зрения, внутреннего — образы, воспоминания, сновидные образы. деконцентрации внимания позволяет отследить переходы от поля
зрения к образной продукции.
деконцентрации внимания не обязательно проводить, начиная от периферии поля зрения —
степень дифференцированное™ визуальных образований одинакова
в центре и по краям. Поле зрения может быть свободным от визуальных
неоднородностей, но даже в однородном темном фоне можно различить
тысячи появляющихся и исчезающих точек. деконцентрации внимания должна распространиться и на эти мельчайшие неоднородности, что создает предпосылки
для более сильного сдвига текущего состояния, чем при обычной деконцентрации внимания.
При достаточно длительной деконцентрации внимания внимание смещается от неопределенных пятен к возникающим образам. Можно наблюдать трансформацию
отдельных пятен в образы, появление образов в глубине за визуальными
сгущениями или движущиеся фигуры, которые относятся не к перцептивным, а имагинативным феноменам.
Перцептивно-имагинативные переходы сопровождаются и изменением субъективной локализации — от пребывания в реальности бодрствования можно перейти в реальности просоночного или сновидного миров.
Именно эти переходы придают особую специфику визуальной деконцентрации внимания при
закрытых глазах, в отличие от деконцентрации внимания при открытых глазах, которая балансирует на грани восприятия однородного визуального фона и выделения
из него отдельных фигур. Наблюдения перцептивно-имагинативных переходов требует такой разотождествленности «Я» с содержаниями сознания,
которое позволяет не вовлекаться в спонтанные процессы погружения во
внешний, перцептивный или во внутренний, имагинативный миры.
Переход от визуальной деконцентрации внимания при закрытых глазах к обычной деконцентрации внимания
позволяет отработать два способа усиления деконцентрации внимания. Открывая и закрывая глаза, практикующий полностью изменяет «визуальную картинку»
и вновь появившиеся фигуры в поле восприятия становятся гораздо более «агрессивными», притягивающими к себе внимания за счет рефлекса сосредоточения внимания на появившемся или изменившемся объекте. Сознание стремится узнать новые визуальные объекты, понять,
что появилось перед ним, а для этого необходимо выделить новый объект из фона, придать ему предметность, что и обеспечивается «сгущением» внимания на нем. Преодоление разрушающего влияния тотальной
смены визуального поля — задача не менее сложная, чем достижение
третьей стадии визуальной деконцентрации внимания. Переходы от одного визуального поля
к другому позволяют отработать деконцентрации внимания достаточной глубины, «накачать
деконцентрации внимания-мышцы».
Другой прием, усиливающий деконцентрации внимания — равномерное распределение внимания по полю зрения при закрытых глазах с превращением визуального
поля в однородный фон — описан в 3.3. Когда достигнута достаточная
равномерность свечения или «темноты», переход к деконцентрации внимания с открытыми глазами позволяет «разгладить» поле зрения, сделать деконцентрации внимания столь же равномерной, что и в предшествующем режиме.


=== Техники формирования аудиальной деконцентрации внимания
деконцентрации внимания по звуковому полю выстраивается аналогично визуальной деконцентрации внимания.
Здесь также действует принцип распространения внимания от менее
дифференцированных зон восприятия к более организованным. Для слухового восприятия такие менее дифференцированные зоны подобрать
достаточно сложно. Здесь действуют три принципа.
Во-первых, уравнивается значимость сильных и слабых стимулов —
внимание фиксирует одновременно громкие и тихие звуки, не допуская
преимущественного выделения громких звуков. Стереотип реагирования
подавляется сравнительно быстро. Критерий достаточно прост: реакция
на громкие и новые звуки (ориентировочная реакция) не превышает реакции на тихие и привычные.
Во-вторых, разрываются связи звуков и их источников. Обычно звуки составляют связное целое, поскольку соотносятся с теми предметами
или процессами, которые их производят. В противоположность этому
в аудиодеконцентрации внимания нужно тщательно отследить и устранить зрительные и смысловые ассоциации. Звуки лишаются смысловой наполненности, превращаются в «просто звуки».
И, наконец, подавляется тенденция формирования из последовательности звуков устойчивых гештальтов (мелодия, ритм и т.д.). Это самая сложная часть работы. Нужно суметь воспринять ритмичную мелодию как набор одиночных, не связанных друг с другом звуков. Условием
успешной аудиодеконцентрации внимания становится обессмысливание, десемантизация
звуков. Лишенные объединяющей смысловой основы, звуковые фигуры
распадаются на набор отдельных звучаний. В этот момент разрывается
связь звуковых форм и соответствующих им смысловых зон сознания,
и внимание сравнительно легко перемещается на эти зоны, сосредоточиваясь на той основе, из которой возникают и которая несет в себе звуки—на ходе времени.
Десемантизированные звуки, тем не менее, стремятся к образованию
устойчивых фигур и начинают объединяться по-новому — не источником происхождения и не звуковым гештальтом, а моментом времени,
в который они достигают барабанной перепонки. Таким образом, в сознании возникает еще одна характеристика времени, обычно скрытая от
осознания под звуковыми потоками — актуальное настоящее.
Актуальное настоящее — это то, что воспринимается как настоящее,
как происходящее «сейчас», а не в прошлом или будущем. Это не физическая абстракция грани «между прошлым и будущим». Актуальное настоящее всегда имеет определенную длительность, которая колеблется
в зависимости от характера приходящих стимулов. Последовательность
звуков воспринимается как звуковая фигура только тогда, когда все ее
элементы воспринимаются как актуально существующие сейчас. В пределах актуального настоящего последующее событие влияет на предыдущее. Актуальное настоящее — это целостность, «квант времени».
Максимальная длительность актуального настоящего определяется
временем восприятия предложения, в котором последнее слово определяет первое («Коса у девушки расплелась» и «Коса у девушки порезала
ногу» — о какой косе идет речь, становится понятным только после третьего слова, но субъективно значение слова «коса» определяется «с самого
начала», т.е. фраза воспринимается как единое целое). В качестве длительности актуального настоящего, группирующего звуки различного происхождения в единый паттерн, обычно принимается 0,5-1,5 секунды.
Звуки существуют во времени, и звуковая последовательность одномерна по своей природе. Аудиодеконцентрации внимания можно считать устойчивой, если внимание
скользит вдоль звукового потока, не увеличивая и не сокращая интервал
актуального настоящего. Этому способствуют практики целенаправленного формирования и удержания в сознании различных звуковых фигур.
Усилия по переводу аудиодеконцентрации внимания в фоновое восприятие по аналогии
с визуальной деконцентрации внимания приводят к неожиданному результату. Если визуальный фон воспринимается как «винегрет», составленный из не связанных
между собой фрагментов зрительного поля, то звуковой фон, то, что находится между звуками — это время, точнее, промежуточное переживание между звуковой «первоматерией» и ходом времени.

=== Соматическая деконцентрации внимания
Соматическая деконцентрации внимания формируется по той же логике, что и визуальная —
от менее дифференцированных восприятий к более дифференциро
ванным. В качестве первичного малодифференцированного объекта
внимания выбирается то неопределенное чувство теплоты, которое
обнаруживает каждый человек, обративший внимание вглубь своего
тела. От этого неопределенного переживания внимание перемещается
к основным зонам тела — голове, груди, животу, рукам и ногам. Лучший
результат получается, если фиксировать не сами ощущения, а различия
в ощущениях разных зон тела. Как и в других видах деконцентрации внимания, внимание не
должно перемещаться от одной зоны к другой, а одновременно фиксировать ощущения всех зон сразу.
Следующий шаг — распространение внимания на более дробные зоны
(пальцы, суставы, язык, печень и т.д.), после чего остается ввести в поле
внимания все тактильные ощущения и соматическая деконцентрации внимания сформирована.
Ощущения, которые фиксируются вниманием, не должны соотноситься со зрительной схемой тела. Ощущения как бы «висят в пространстве»
однородной массой.
Точно так же, как и при визуальной деконцентрации внимания, внимание при соматической
деконцентрации не может долго удержать множество отдельных точечных ощущений и срывается в общее переживание соматического фона.
Это некое недифференцированное, разлитое по всему телу однородное
ощущение. Соматический фон легко колеблется при изменении окружающей среды — новых звуках, появлении новых лиц и т.д.
Можно выделить по меньшей мере две составляющие в соматическом фоне: качественную (события окружающего и внутреннего мира
отзываются в фоне различным качеством ощущений) и «энергетическую»
(громкие или неожиданные звуки и другие стимулы разной природы,
как правило, повышают общий тонус, действия практикующего могут
его повышать или понижать). При соответствующей тренировке качественные колебания соматического фона могут служить индикатором
слабых или скрытых стимулов (так, некоторые люди «спиной ощущают опасность») и средой развертывания различных смыслов. Фиксация
энергетического фона позволяет осознанно повышать общий тонус организма и извлекать энергию из различных стимулов и изменений окружающей и внутренней среды.

=== Фон

Конечным итогом деконцентративных техник является выход на фоновые переживания различной модальной природы. Дальнейшее движение
в этом направлении практики порождает другой класс состояний — переживание «не-форм» и «не-восприятий». Фон не фигуративен по определению. Это то, что находится между фигурами, окружает фигуры.
На первых шагах изучения дЕКОНЦЕНТРАЦИИ ВНИМАНИЯ его поддержание требует постоянных усилий, поскольку существует тенденция превращения однородного фона в фигуративное восприятие или фигуративную имагинацию.
Внимание как функция стремится к выделению отдельных фигур, и прекращение такого выделения означает приостановку работы внимания.
Описание фона в языке, который по природе своей является орудием
описания фигур, затруднительно по причине его континуального характера. Фон можно только назвать и противопоставить предметному восприятию, но обозначения операций с фоном не разработаны. Поэтому
инструкции могут вывести восприятие за пределы фигуративное,
обозначить операции над фоном метафорически, но дать столь подробные предписания действий с фоном и внутри фона, как это легко делается в отношении фигуративного мира, просто невозможно.

=== Использование деконцентрации внимания-техник
Практическое использование деконцентрации внимания-техник значительно шире, чем может
показаться. Остановимся на двух примерах: на фри-дайвинге и конном
спорте. Наталья Молчанова, тренер команды и чемпион мира по фридайвингу объясняет необходимость использования дЕКОНЦЕНТРАЦИИ ВНИМАНИЯ во фри-дайвинге
следующим образом:
«При "пустом" сознании, или "остановке внутреннего диалога", возникающих при деконцентрации внимания, легче осуществляется интеграция нейронной активности различных участков коры больших полушарий
и подкорковых структур с целью наилучшего восприятия значимого
сигнала. Это позволяет быстрее реагировать на изменения ситуации
при нырянии и адекватно реагировать...
При подъеме из глубины важно активно сканировать свое состояние, "собираться", так как иногда при всплытии вследствие
стремительного падения напряжения кислорода в крови и развития острой гипоксии фридайвер "засыпает" — теряет сознание
без каких-либо предварительных дискомфортных ощущений. Это
возможно при врожденной или приобретенной благодаря адаптации к гипоксическим тренировкам низкой чувствительности
к высокому содержанию углекислого газа в крови.
Одним из главных условий осознания стимула является его интенсивность. Сильный раздражитель (в данном случае гиперкапния) всегда проникает в сознание. Но у людей с высоким порогом
активации хеморецепторов, посылающих импульсацию в дыхательный центр, сигнал о возобновлении дыхания остается неосознанным.
В этом случае при необходимости выявления слабых и скрытых признаков весьма результативной является соматическая деконцентрации внимания
с распределением внимания по всему объему тела и позволяющая
тонко улавливать любые колебания соматического фона.
Совмещение аудио-деконцентрации внимания, визуальной и соматической деконцентрации приводит к интеграции сигналов в коре головного мозга.
Межсенсорное взаимодействие на корковом уровне создает условия для формирования "картины мира" и координации поведения
организма.
Таким образом, происходит гармоничное взаимодействие ныряльщика с внешней средой и улавливаются малейшие колебания
внутренней среды организма, а процессы принятия решений и исполнения осознаются минимально и протекают с незначительным
контролем со стороны разума в темпе требований ситуации».
Другой пример — использование деконцентрации в конном спорте
при подготовке спортсменов. Автор — С. Свифт — самостоятельно пришла к формулировке метода, позволяющего эффективно контролировать
поведение лошади. Она назвала этот метод «мягкими глазами». Суммарно
«мягкие глаза» описываются следующим образом:
«Чем большую область вы охватываете глазами, тем лучше чувствуете свою посадку».
«Основные принципы «мягких глаз»:
При езде широко раскройте глаза и активизируйте периферическое
зрение.
Продолжайте осознавать все находящееся в поле зрения.
Находите внутренний отклик тому, что вы видите глазами.
Результаты применения:
Увеличивается поле зрения.
Более остро сознается свое тело и тело лошади.
Уменьшается напряжение.
Движение вперед становится легче и свободнее».
Очевидно совпадение техник «мягких глаз», деконцентрации внимания и результатов с начальными стадиями деконцентрации внимания.