= Aktyvi sąmonė.
v1.0, 2020-06-07
:example-caption!:
:sectnums:
:sectnumlevels: 3

= 1. Skirsnis. Psichonetinės technikos

== Skyrius. Valios psichotechnikos bendrame psichotechnikų kontekste
== Skyrius. Valios psichotechnikos: principai ir apibrėžimai
== Skyrius. Valios meditacija
=== Atlikimo technika
Valios meditacija yra pagrindinė technika psichonetiniame darbe. Jos paskirtis - pasiekimas trijų tarpusavyje susijusių
pozicijų. Tai:

intensyvus realaus sąvojo "Aš" pergyvenimas;

"Aš" atskyrimas nuo bet kokių sąmonės turinių ir formų;

vidinės laisvės nuo stimulų, valdančių sąmonę patirties įgyjimas;

Valios meditacija tai ne vienų psichinių darinių darbas su kitais, ne jų tarpusavio saveika, tai iškelto už bet kokių
sąmonės
organizuotumų "Aš" darbas su visu psichikos totalumu.

Nereikia galvoti, kad valios meditacija tai valios veiksmas. Pradinėse valios meditacijos mokymosi stadijose valios
meditacija vaizduoja valios veikimą, yra
atvaizdas, imitacija, bet ne valios pažadinimas, nors, be abejo, valios meditacija - ryškiausiai imituoja valios
realybes. Nėra valios veiksmo išprovokavimo būdo,
bet imituojant jį, galima įgyti supratimą apie tai, kaip valia susijusi su Pasaulio sąlygotumo aspektais. Praktikos eigoje valios veikimo imitacija
palaipsniui priartina prie realybės ir, galiausiai, pažadina valią.

Valios meditacijos atlikimui reikia užimti patogią padėtį. Pageidautina ištiesinti nugarą. Tai nėra ritualinio pobūdžio reikalavimas - nesąmoningai
išėjus iš valios meditacijoa praktikas nesugebės išsaugoti tiesios nugaros, tai reikš, kad valios meditacija baigėsi.

Valios meditacija - tai veiksmas, kylantis ne iš "sąmonės organizmo", o iš siekiančio valios būsenos "Aš". Veiksmas,
principe, gali būti bet koks, bet geriau, kada jame koncentruotu pavidalu būtu valios meditacijos idėja. Veiksmui, kurį
atlieka
"Aš", pasirenkamos dvi formulės, kurios yra valios meditacijos idėjos verbalinis išpakavimas.

Pirma valios meditacijos formulė - "Aš esu". Tai sena, daugybėje praktikų naudojama formulė, teigia, pirma,
sakančiojo šią formulę egzistavimo ir atsakomybės už savo egistavimo faktą (tai sukelia ryškų savojo "Aš"
pergyvenimą), ir, antra, atskiria gryną "Aš" (stebinčią ir veikiančią instanciją) nuo viso sąmonės turinio.

Egzistavimo realumo patirtis - tai ne trivialus veiksmas. Daugumas žmonių gyvena savo gyvenimą nesuvokdami
"Aš" realumo, o tarsi žiūrėdami kiną apie savo gyvenimą, bet ne valdydami jį aktyviai. Idėjinis "Aš esu" formulės
komponentas (jeigu dėmesys susitelkęs ant tos idėjos) priverčia pajausti susitelkimą ties savimi, savęs
kompaktiškumą, išskirtinumą bendrame Kosmoso audinyje. Tai visai ne banali savęs ir Pasaulio priešprieša, tai,
greičiau, trancencendentinės ir imanantinės sąmonės sudedamųjų dalių atskyrimas. Transcendentinis, stebintis ir
veikiantis "Aš" prieš visas žmogiškosios būtybės sudedamąsias dalis, kurios įtrauktos į bendrą gyvenimo strautą,
atspindi šį srautą ir priklauso nuo jo.

"Aš" atskyrimas nuo viso kito sudaro antrą valios meditacijos komonentą. "Aš esu" apeliuoja į gryno "Aš" patirties ir aktualios
psichinės struktūros nesutapimą. Tuo pačiu sukuriamos poveikio sąmonės struktūroms ir sąmonės procesams prielaidos -
subjekto ir objekto veiksmai aiškiai atskiriami vienas nuo kito. Vis dėl to negalima sakyti, kad valios meditacijoje
"Aš" nuo pat pradžių veikia kaip valios subjektas. Čia, greičiau, "Aš" veikia taip, tarsi valios "Aš" aspektas būtų
pažadintas. Valios meditacijoje nėra pagrindinės valios veiksmo charakteristikos - jo besąlygiškumas išorinėms
prižastims. Yra priežastis - užsiėmimų vadovo tekstas arba instrukcija, bet yra ir vidinis veiksmas - nutarimas vykdyti
valios meditaciją. Nuo nutarimo atlikti valios meditaciją vykdoma kaip valios veiksmą imituojanti procedūra ir kuo
toliau realios
sąlygos (tiek
išorinės, tiek vidinės) nuo sąlygų, kuriose buvo nutarta pradėti valios meditaciją, tuo valios meditacija darosi
sąmoningesnė ir
artimesnė valios
veiksmui.

Antroji valios meditacijos formulė - "Aš esu valia". Šios formulės idėja skiriasi nuo "Aš esu". Jeigu "Aš esu" teigia tik realų "Aš"
egzistavimo faktą, tai "Aš esu valia" pabrėžia "Aš" aktyvumą. Ritmiškas formulių kaitaliojimas abipusiai stiprina
viena kitą. "Aš esu valia" imituoja ir tuo pačiu provokuoja trečią valios meditacijos komponentą - besąlygišką veiksmą. Bet koks
sąlygotumas iš antros formulės pozicijos laikomas įvykiu, atsirandančiu "Aš" ir valios išorėje.

Valios meditacijos eigoje svarbu išsivaduoti nuo jos formalių išraiškų ir pereiti į idėjų erdvę. Ši užduotis
palengvinama padalinant valios meditaciją į tris fazes.

Pirmoji fazė - tai vidinis formulių tarimas. Tai kalbos aparato veiksmas, audialinis skambesys ir
tariamų frazių idėjos. Pirmoji fazė tesiasi iki stabilaus dėmesio ties formulėmis atsiradimu. Kada pasiektas
stabilumas ir dėmesio blaškymasis minimalizuotas, dadedama antroji fazė - tarimo slopinimas ir susikoncentravimas tik
ties audialiniu skambesiu ir idėjine formulių sudedamąja dalimi. Pirmoje valios meditacijos fazėje dėmesys sutekltas
ties kalbos organais, liežuvis šiek tiek įtempiamas ir, galimai, net juda, imituodamas kalbos garsus. Būtent šie
veiksmai slopinami antrojoje fazėje, o dėmesys sutelkiamas į galvos centrą arba į apimtį tarp ausų.

Antroje fazėje lieka tik skambesys ir formulių idėjos. Skambesys formuojamas vidinėmis pastangomis, formulių idėjos
išpakuojamos į skambesį. Pirmoji ir antroji fazės - tarimas ir skambesio išpakavimai - kaitaliojami ir remia viena kitą.

Kada dėmesio koncentracija ties šiuo dvigubu veiksmu tampa stabilia, dadedama trečioji fazė: išpakuojama tik
atitinkanti formules "Aš esu" ir "Aš esu valia" pozicija. Tam reikia atlikti pastangas, kurios bus nukreiptos į
skambesio išpakavimą, bet vietoje skambesio išpakuoti būseną. Tada valios ketinimas išpakuojamas į būseną, be
garso, be kalbos organų įtempimo, be skambesio. Mes vadiname šią fazę - begarsis formulių išpakavimas.

Pradžioje trečiąją fazę lydi neapibrėžti, bet mobilizuojantys pojūčiai kūne, bet jie turi būti laikomi viena iš
"skambėjimo" formų. Palaipsniui ši forma pakeičiama gryna "Aš esu, Aš esu valia" pozicija, kuri yra ne jaučiamoji,
bet idėjinė patirtis. Praktikos pradžioje trys fazės turi keisti viena kitą, bet pagrindis valios meditacijos
taikinys yra trečioji fazė. Palaipsniui ji turi tapti dominuojančia - vienam pirmų dviejų fazių išpakavimui pradžioje
reikia daryti 2-5, paskui 10 trečių fazės išpakavimų. Pirmoji ir antroji fazės tampa pagalbinėmis, prie kurių
pereinama, kad palaikyti trečiąją.

Pirmoji, antroji ir trečioji fazės turi būti laikomos valios ketinimo išpakavimu, kuris kyla iš "Aš", atliekamas
sąmonės turinio aplinkoje. Visos sąmonės turinyje atsirandančios - mintys, reginiai, atsiminimai, jausmai - laikomi
pašaliniais, "ne savi", esantys už "Aš" ribų. Valios meditacija - tai nuoseklus "Aš" nuo sąmonės turinio atskyrimas.
Bet tai prieštaringas procesas. Idėjinė valios meditacijos sudedamoji dalis išpakuojama į sąmonės turinį, bet
turinį kontroliuoja "Aš". Tik jie yra vidinio aktyvumo produktai. Veikiant empyrinės psichikos ribose, "Aš" sukuria
valios placdarmą tarp sąmonės turinio, kuris sudaro sąmonės organizmo visumą.

=== "Sąmonės organizmo" priešinimasis valios meditacijai

Sąmonės organizmas padarytas iš sąmonės "materijalo", pas šitą organizmą yra savi poreikia ir uždaviniai. Atskyrimas
jame valios "Aš", valios pažadinimas arba bent tokio pažadinimo imitacija, įveda naują vadovaujančią instanciją, kuri
pozicijonuojama virš "sąmonės organizmo". Aišku, "sąmonės organizmas" priešinasi šiai operacijai. Jis bando
"įtraukti" atsiskyrusį "Aš" atgal, užmigdyti valią, pakeisti valios veiksmą jo atvaizdu aktyvios psichikos materiale.

Pirmas priešinimasis - dėmesį blaškančios mintys ir reginiai, kurie magnetizuoja dėmesį. Jie turi būti laikomi
vieninteliam sąmoningam valios meditacijos veiksmui išoriniais trukdžiais.

Antras - nuobodulio ir susierzinimo nuo ilgo pratimo atlikimo atsiradimas, noras kuo greičiau užbaigti valios
meditaciją. Šią būseną reikia taip pat laikyti išoriniu trukdžiu, kuris yra svetimas "Aš", kaip tai, kas trukdo
atlikti valios meditaciją.

Trečias priešinimosi tipas - svarbių, ryškių ir idomių minčių, įžvalgų, idėjų, kurias norisi apgalvoti, apžvelgti,
užsirašyti atsiradimas. Tam sunku priešintis, tarp šių minčių pasitaiko iš tiesų svarbios ir vertingos idėjos. Bet
šias mints, jų svarbos vertinimą reikia taip pat laikyti "sąmonės organizmo", besistengiančio nutraukti valios
meditaciją veikla.

Galiausiai, pats subtiliausias priešinimasis - valios meditacijos imitacija. Meditatorius pradeda tarti formules
automatiškai, nejausdamas jų prasmės. "Sąmonės organizmas" stropiai atkuria valios meditacijos fenomenologiją,
slopindamas patį svarbiausią - naujo psichikos valdymo centro atsiradimą, kuris nepriklausomas sąmonės organizmo
sąlygotumo. Čia svarbu skirti - kas atsiranda iš valios "Aš" ir kas ateina iš išorės, iš "sąmonės organizmo".
Kriterijumi gali pasitarnauti valios meditacijos nutraukimo pagrindo buvimas arba nebuvimas be praktiką atliekančio
nutarimo, kuris gimsta iš valios "Aš". Valios meditacijos parktikoje jokie išriniai ir vidiniai įvykia, kokie svarbūs
bebūtų "sąmonės organizmui", nėra valios meditacijos nutraukimo pagrindas, nes valios meditacijos valdymas gimsta
valios "Aš", o ne iš atskirų aktualios psichikos aspektų.

=== Valios meditacijos atskyrimas nuo psichinių procesų

